
stages:
    - build
    - deploy

cache:
  paths:
    - node_modules/

image: jbuncle/node-build-docker

build-and-tag:
    stage: build
    before_script:
        - npm config set strict-ssl false
        - npm config set registry https://nexus.jbuncle.co.uk/repository/npm/
    script:
        - npm install
        - npm run build
        - gitlab-tag
    only:
        - master

pack:
    stage: build
    before_script:
        - npm config set strict-ssl false
        - npm config set registry https://nexus.jbuncle.co.uk/repository/npm/
    script:
        - npm install
        - npm run build
        - npm pack
    artifacts:
        paths:
            - '*.tgz'
    only:
        - tags

publish:
    stage: deploy
    before_script:
        - npm config set strict-ssl false
        - npm config set registry https://nexus.jbuncle.co.uk/repository/npm-private/
    script:
        - RELEASE="$(ls *.tgz | tail -n 1)"
        - echo $RELEASE
        - npm publish $RELEASE
    only:
        - tags
    dependencies: 
        - pack
